### PR TITLE
added metrics option and argparse cmdline parsing

### PR DESCRIPTION
**Pull request by MarcoDuiker**
I added an option to ellie so we can see the results in metrical units (km and meters).

I added command line parsing with the argparse module so a help is available.

By the way:
On studying the results in metrical units I see that the results on distance and speed are way off.
On a track with a length of about 350 km ellie  reports more than 500 km. (this has nothing to do with conversion to km, if I use ellie in miles I see the same mistake).

### CODE REVIEW

**Comment by akkana** [comment]
That's great! It would be great to have metric, and converting to argparse is something it has needed for a long time.

Only one problem: it looks like you reverted some of my recent changes (an easy check: the key_press_event code near the end is gone) and your patch doesn't quite run with current head: it dies at lat, lon, ele, t = pt because pt isn't a tuple. I have a local fix for that, but before I merge and check in I'm trying to understand why your branch and head get such different values for both miles and elevation. On a test hike picked at random, head shows 5.6 miles and 1188', your branch shows 5.2 miles and 1201. I think I had some improvements to the distance measurement (I agree that it over-estimates, and I've been trying to fix that; I think with my recent changes it was probably still off, but less so) and maybe your changes reverted some of those? I need to do more code analysis on the patch and figure out where the differences are coming from.

**Comment by akkana** [comment]
Actually, if I check head against a hiking book, the mileages and elevations are reasonably close, though sometimes I have to adjust halfwidth (-w) for the smoothing to get reasonable climb numbers.

Is there any way you could make a pull request that just included your fixes, without reverting all the other calculations? I could probably copy just the relevant parts out of your PR diffs, but then they wouldn't show up as your changes in git.

**Comment by MarcoDuiker** [comment]
Hmm, actually I first installed with pip install and had a working Ellie.

Then I tried to clone from GitHub and use Ellie from that and ran in some errors. So I decided to revert to the version in pip rather than in GitHub and work from there.

So, I can make  a pull request which include only my fixes, but then it won't be working.
I suggest you adapt your code with whatever you like from my pull request. I don't mind that the changes won't show up as mine in git.

**Comment by akkana** [comment]
I've merged in the metric and the argparse stuff, credited to you. Thanks!

What problems did you run into with the github version? I see when I try to install to a virtualenv that I get an error installing /usr/share/pixmaps/pytopo.png; I'll work on fixing that. There might be platform issues installing on non-linux too, but I have no way of testing that, so I'd be interested in hearing about them if there are any. It's probably getting to be time for a new pypi release anyway, but I'd like to experiment a bit first with seeing if I can get ellie to choose the right halfwidth value.

**Pull request closed without merging**
